### ISSUE TITLE
The screen of obs studio upper part is not visible in fedora 

### ISSUE THREAD

**Issue by sparkingdark** [Xaymar/obs-StreamFX#339] opened 2020-09-26 07:26 UTC
### Description
When i open the app in fedora it is only showing the lower portion not the upper portion kind of hollow screen in the screen.take a look in picture.I installed it via snap.

[The picture](https://pasteboard.co/JsPMzbp.png)

### System Information

- Software Version: 25.0.8
- Operating System: Fedora
- Kernel Version: 5.8.9-200.fc32.x86_64 
- CPU: Intel i3-6006U (4) @ 2.000GHz 
- GPU: Intel HD Graphics 520 
- GPU: NVIDIA GeForce MX110 
- Memory: 1961MiB / 3794MiB

**Comment by skeletonbow** [comment] 2020-09-26 08:05
Are you having a problem with OBS Studio?  StreamFX is just a 3rd party plugin for OBS, it isn't the application itself.  I think you filed this bug against the wrong product perhaps?

**Comment by Xaymar** [comment] 2020-09-26 13:42
Possible duplicate of #326

**Comment by Xaymar** [comment] 2020-09-26 13:43
Fedora is not officially supported, you will have to contact the maintainers for the packages of that platform.

**Comment by Picoseconds** [comment] 2020-09-26 16:48
Are you using Wayland? OBS does not support Wayland.

**Comment by sparkingdark** [comment] 2020-09-27 04:33
Yes similar to the #326

**Comment by Xaymar** [comment] 2020-09-27 05:13
> I installed it via snap.

Do you mean this package? https://snapcraft.io/obs-studio

If so, their support is provided here: https://github.com/snapcrafters/obs-studio/issues

**Comment by Xaymar** [comment] 2020-09-27 05:20
Closing this as it is an OBS Studio problem:

- https://github.com/obsproject/obs-studio/pull/2478
- https://github.com/obsproject/obs-studio/pull/2482
- https://github.com/obsproject/obs-studio/pull/2484

Also tracked by the snap package here it seems: https://github.com/snapcrafters/obs-studio/issues/50

**Closed by Xaymar** 2020-09-27 05:20 UTC
Labels: os:linux, os:unsupported, type:support
