### ISSUE TITLE
OBS crashing when removing dynamic mask filter

### ISSUE THREAD

**Issue by jemmell** [Xaymar/obs-StreamFX#385] opened 2020-11-25 18:30 UTC
### Description

Experiencing regular OBS crashes when removing a dynamic mask effect from a scene. After the crash the filter is still there. Also occurs when moving the dynamic mask order/priority with other filters on the same scene.

[2020-11-25 13-28-25.txt](https://github.com/Xaymar/obs-StreamFX/files/5598601/2020-11-25.13-28-25.txt)
[2020-11-25 13-27-19.txt](https://github.com/Xaymar/obs-StreamFX/files/5598602/2020-11-25.13-27-19.txt)
[2020-11-25 13-18-16.txt](https://github.com/Xaymar/obs-StreamFX/files/5598603/2020-11-25.13-18-16.txt)
[2020-11-25 13-11-59.txt](https://github.com/Xaymar/obs-StreamFX/files/5598604/2020-11-25.13-11-59.txt)
[2020-11-25 10-43-42.txt](https://github.com/Xaymar/obs-StreamFX/files/5598605/2020-11-25.10-43-42.txt)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST] 26.0.2
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5598569/DxDiag.txt)

**Comment by Xaymar** [comment] 2020-11-26 15:17
Please also upload the crash log, as just the log files themselves don't help much.

**Comment by Xaymar** [comment] 2020-11-29 00:12
Possibly the same underlying bug as #384

**Comment by Xaymar** [comment] 2021-01-21 02:38
Unable to reproduce the issue, and no crash log was provided for ~2 months after reporting the issue. Closing as invalid.

**Closed by Xaymar** 2021-01-21 02:38 UTC
Labels: type:support
