### ISSUE TITLE
[BUG] (Good day. Just updated to OBS 27 and StreamFX 0.10.1.0 and new Nvdia driver. StreamFx autotracking plugin no longer works. Worker perfectly with order version and obs 26)

### ISSUE THREAD

**Issue by dahalday** [Xaymar/obs-StreamFX#566] opened 2021-06-05 23:50 UTC
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0 (including Release Candidates)

### StreamFX Version

0.10.0

### Expected Behavior

Good day. Just updated to OBS 27 and StreamFX 0.10.1.0-gc8484f65 and new NVidia driver 466.63. StreamFx autotracking plugin no longer works. Worker perfectly with order versionStreamFx 0.10.0.0 and OBS 26 and the older NVDIA driver. 

### Current Behavior

NVDIA auto tracking not working

### Steps to Reproduce the Bug

No crashing of OBS. That feature just no longer works

### OBS Studio Log

2021-06-05 19-27-04.txt

### OBS Studio Crash Log

19:27:04.961: CPU Name: AMD FX(tm)-8350 Eight-Core Processor           
19:27:04.961: CPU Speed: 4000MHz
19:27:04.961: Physical Cores: 4, Logical Cores: 8
19:27:04.961: Physical Memory: 16330MB Total, 13393MB Free
19:27:04.961: Windows Version: 10.0 Build 19042 (release: 2009; revision: 630; 64-bit)
19:27:04.961: Running as administrator: false
19:27:04.961: Aero is Enabled (Aero is always on for windows 8 and above)
19:27:04.961: Windows 10 Gaming Features:
19:27:04.961: 	Game Bar: Off
19:27:04.961: 	Game DVR: Off
19:27:04.961: 	Game DVR Background Recording: Off
19:27:04.961: 	Game Mode: Off
19:27:04.964: Sec. Software Status:
19:27:04.966: 	Microsoft Defender Antivirus: enabled (AV)
19:27:04.966: 	Windows Firewall: enabled (FW)
19:27:04.981: Current Date/Time: 2021-06-05, 19:27:04
19:27:04.981: Browser Hardware Acceleration: true
19:27:04.981: Portable mode: false
19:27:06.504: OBS 27.0.0 (64-bit, windows)
19:27:06.504: ---------------------------------
19:27:06.694: ---------------------------------
19:27:06.694: audio settings reset:
19:27:06.694: 	samples per sec: 48000
19:27:06.694: 	speakers:        2
19:27:06.749: ---------------------------------
19:27:06.750: Initializing D3D11...
19:27:06.750: Available Video Adapters: 
19:27:06.752: 	Adapter 0: NVIDIA GeForce RTX 2060 SUPER
19:27:06.752: 	  Dedicated VRAM: 4126146560
19:27:06.752: 	  Shared VRAM:    4267034624
19:27:06.752: 	  PCI ID:         10de:1f06
19:27:06.753: 	  Driver Version: 27.21.14.6663
19:27:06.753: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=75, name=SB220Q
19:27:06.756: Loading up D3D11 on adapter NVIDIA GeForce RTX 2060 SUPER (0)
19:27:06.892: D3D11 loaded successfully, feature level used: b000
19:27:06.892: DXGI increase maximum frame latency success
19:27:06.892: D3D11 GPU priority setup failed (not admin?)
19:27:07.807: ---------------------------------
19:27:07.807: video settings reset:
19:27:07.807: 	base resolution:   1920x1080
19:27:07.807: 	output resolution: 1920x1080
19:27:07.807: 	downscale filter:  Lanczos
19:27:07.807: 	fps:               30/1
19:27:07.807: 	format:            NV12
19:27:07.807: 	YUV mode:          709/Full
19:27:07.807: NV12 texture support enabled
19:27:07.818: Audio monitoring device:
19:27:07.818: 	name: Speakers (Realtek High Definition Audio)
19:27:07.818: 	id: {0.0.0.00000000}.{691a549c-580b-48cc-9cdf-010dbe6e0558}
19:27:07.919: ---------------------------------
19:27:07.929: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
19:27:07.987: Skipping module '../../obs-plugins/64bit/concrt140.dll', not an OBS plugin
19:27:08.015: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
19:27:08.046: Failed to load 'en-US' text for module: 'decklink-captions.dll'
19:27:08.130: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
19:27:08.332: [AMF] Unable to load 'amfrt64.dll', error code 126.
19:27:08.334: [AMF] AMF Test failed due to one or more errors.
19:27:08.334: Failed to initialize module 'enc-amf.dll'
19:27:09.496: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
19:27:09.519: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
19:27:09.606: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
19:27:09.717: Skipping module '../../obs-plugins/64bit/msvcp140.dll', not an OBS plugin
19:27:09.835: [obs-browser]: Version 2.14.3
19:27:09.835: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
19:27:10.300: NVENC supported
19:27:10.361: [noise suppress: Nvidia RTX denoiser disabled, redistributable not found]
19:27:10.508: [obs-ndi] hello ! (version 4.9.0)
19:27:10.508: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
19:27:10.509: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
19:27:10.791: [obs-ndi] NDI runtime loaded successfully
19:27:12.239: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
19:27:12.811: Failed to load 'en-US' text for module: 'obs-ptzcontroller.dll'
19:27:14.648: [obs-websocket] you can haz websockets (version 4.8.0)
19:27:14.648: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.15.2
19:27:14.748: [obs-websocket] module loaded!
19:27:14.846: Skipping module '../../obs-plugins/64bit/Qt5Network.dll', not an OBS plugin
19:27:14.848: Module '../../obs-plugins/64bit/Qt5Network.dll' not loaded
19:27:14.950: Skipping module '../../obs-plugins/64bit/SDL2.dll', not an OBS plugin
19:27:15.025: Failed to load 'en-US' text for module: 'StreamDeckPlugin.dll'
19:27:15.324: [StreamFX] Loading Version 0.10.1.0-gc8484f65
19:27:19.551: [StreamFX] Loaded Version 0.10.1.0-gc8484f65
19:27:19.639: Skipping module '../../obs-plugins/64bit/ucrtbase.dll', not an OBS plugin
19:27:19.702: Skipping module '../../obs-plugins/64bit/vccorlib140.dll', not an OBS plugin
19:27:19.713: Skipping module '../../obs-plugins/64bit/vcruntime140.dll', not an OBS plugin
19:27:19.913: VLC found, VLC video source enabled
19:27:20.645: Decklink API Compiled version 11.6
19:27:20.645: Decklink API Installed version 11.4
19:27:21.239: ---------------------------------
19:27:21.239:   Loaded Modules:
19:27:21.239:     win-wasapi.dll
19:27:21.239:     win-mf.dll
19:27:21.239:     win-dshow.dll
19:27:21.239:     win-decklink.dll
19:27:21.239:     win-capture.dll
19:27:21.239:     vlc-video.dll
19:27:21.239:     text-freetype2.dll
19:27:21.239:     StreamFX.dll
19:27:21.239:     StreamDeckPlugin.dll
19:27:21.239:     rtmp-services.dll
19:27:21.239:     obs-x264.dll
19:27:21.239:     obs-websocket.dll
19:27:21.239:     obs-vst.dll
19:27:21.239:     obs-transitions.dll
19:27:21.239:     obs-text.dll
19:27:21.239:     obs-qsv11.dll
19:27:21.239:     obs-ptzcontroller.dll
19:27:21.239:     obs-outputs.dll
19:27:21.239:     obs-ndi.dll
19:27:21.239:     obs-filters.dll
19:27:21.239:     obs-ffmpeg.dll
19:27:21.239:     obs-browser.dll
19:27:21.239:     image-source.dll
19:27:21.239:     frontend-tools.dll
19:27:21.239:     enc-amf.dll
19:27:21.239:     decklink-ouput-ui.dll
19:27:21.239:     decklink-captions.dll
19:27:21.239:     coreaudio-encoder.dll
19:27:21.239: ---------------------------------
19:27:21.294: ==== Startup complete ===============================================
19:27:21.589: Switched to Preview/Program mode
19:27:21.589: ------------------------------------------------
19:27:21.693: All scene data cleared
19:27:21.693: ------------------------------------------------
19:27:22.196: WASAPI: Device 'Speakers (Realtek High Definition Audio)' [48000 Hz] initialized
19:27:22.278: [Loaded global audio device]: 'Desktop Audio'
19:27:22.278:     - monitoring: monitor and output
19:27:22.332: WASAPI: Device 'Analogue 1 + 2 (Focusrite Usb Audio)' [96000 Hz] initialized
19:27:22.539: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed.
19:27:22.545: adding 213 milliseconds of audio buffering, total audio buffering is now 213 milliseconds (source: Wing AUX Out Main Mix)
19:27:22.545: 
19:27:23.089: [Loaded global audio device]: 'Wing AUX Out Main Mix'
19:27:23.089:     - filter: 'Noise Suppression' (noise_suppress_filter)
19:27:23.089:     - filter: 'Compressor' (compressor_filter)
19:27:23.089:     - filter: 'Gain' (gain_filter)
19:27:23.089:     - filter: 'Noise Gate' (noise_gate_filter)
19:27:23.089:     - filter: 'VST 2.x Plug-in' (vst_filter)
19:27:23.089:     - monitoring: monitor and output
19:27:23.211: WASAPI: Device 'IN 1-2 (BEHRINGER WING-USB)' [48000 Hz] initialized
19:27:23.212: [noise suppress: 'Noise Suppression'] NVAFX redist is not installed.
19:27:23.213: [Loaded global audio device]: 'Wing  UBS Out Main  Mix'
19:27:23.213:     - filter: 'Gain' (gain_filter)
19:27:23.213:     - filter: 'Compressor' (compressor_filter)
19:27:23.213:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
19:27:23.281: [obs-ndi] started A/V threads for source 'CENTRALGOSPEL (SongShow Plus, OBS)'
19:27:23.282: [obs-ndi] A/V thread for 'Priase Lower Thirds' started
19:27:23.477: [Media Source 'Openeing_Music']: settings:
19:27:23.477: 	input:                   C:/Users/admin/Videos/Opening/Worship music with Sister Margaret.mp4
19:27:23.477: 	input_format:            (null)
19:27:23.477: 	speed:                   100
19:27:23.477: 	is_looping:              no
19:27:23.477: 	is_hw_decoding:          no
19:27:23.477: 	is_clear_on_media_end:   yes
19:27:23.477: 	restart_on_activate:     yes
19:27:23.477: 	close_when_inactive:     no
19:27:23.483: [Media Source 'Opening Video']: settings:
19:27:23.483: 	input:                   D:/CGCP/Videos/OBS Videos to Stream/Virtual Entrance.mp4
19:27:23.483: 	input_format:            (null)
19:27:23.483: 	speed:                   100
19:27:23.483: 	is_looping:              no
19:27:23.483: 	is_hw_decoding:          no
19:27:23.483: 	is_clear_on_media_end:   yes
19:27:23.483: 	restart_on_activate:     yes
19:27:23.483: 	close_when_inactive:     no
19:27:23.495: [obs-ndi] started A/V threads for source 'CENTRALGOSPEL (BibleShowNDI)'
19:27:23.496: [obs-ndi] A/V thread for 'BibleShow' started
19:27:27.304: ---------------------------------
19:27:27.304: [DShow Device: 'Camera 1'] settings updated: 
19:27:27.304: 	video device: Decklink Video Capture
19:27:27.304: 	video path: 
19:27:27.304: 	resolution: 1920x1080
19:27:27.304: 	flip: 0
19:27:27.304: 	fps: 59.94 (interval: 166833)
19:27:27.304: 	format: HDYC
19:27:27.397: ---------------------------------
19:27:27.397: [DShow Device: 'Screen 2'] settings updated: 
19:27:27.397: 	video device: FHD Capture
19:27:27.397: 	video path: \\?\usb#vid_1bcf&pid_2c99&mi_00#7&264f6503&1&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
19:27:27.397: 	resolution: 1920x1080
19:27:27.397: 	flip: 0
19:27:27.397: 	fps: 60.00 (interval: 166666)
19:27:27.397: 	format: YUY2
19:27:52.073: warning: deprecated pixel format used, make sure you did set range correctly
19:27:52.206: warning: deprecated pixel format used, make sure you did set range correctly
19:27:52.246: [Media Source 'Count down']: settings:
19:27:52.246: 	input:                   C:/Users/admin/Videos/RealTimes/RealDownloader/2 Minute Countdown Timer.mp4
19:27:52.246: 	input_format:            (null)
19:27:52.246: 	speed:                   100
19:27:52.246: 	is_looping:              no
19:27:52.246: 	is_hw_decoding:          no
19:27:52.246: 	is_clear_on_media_end:   yes
19:27:52.246: 	restart_on_activate:     yes
19:27:52.246: 	close_when_inactive:     no
19:27:52.250: [Media Source 'Closing Video']: settings:
19:27:52.250: 	input:                   D:/CGCP/Videos/OBS Videos to Stream/Closing II.mp4
19:27:52.250: 	input_format:            (null)
19:27:52.250: 	speed:                   100
19:27:52.250: 	is_looping:              no
19:27:52.250: 	is_hw_decoding:          no
19:27:52.250: 	is_clear_on_media_end:   no
19:27:52.250: 	restart_on_activate:     yes
19:27:52.250: 	close_when_inactive:     no
19:27:52.261: [obs-ndi] started A/V threads for source 'DESKTOP-ENQ9SG1 (BibleShowNDI)'
19:27:52.262: [obs-ndi] A/V thread for 'Stream BibleShow' started
19:27:52.492: Switched to scene 'Left Cam'
19:27:52.530: ------------------------------------------------
19:27:52.530: Loaded scenes:
19:27:52.530: - scene 'Left Cam':
19:27:52.530:     - source: 'Camera 1' (dshow_input)
19:27:52.530:         - filter: 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking)
19:27:52.530:     - source: 'CGC' (text_gdiplus)
19:27:52.530:     - source: 'BibleShow' (ndi_source)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530: - scene 'Rigth Cam':
19:27:52.530:     - source: 'Camera2' (dshow_input)
19:27:52.530:     - source: 'CGC' (text_gdiplus)
19:27:52.530:     - source: 'BibleShow' (ndi_source)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530: - scene 'Front Cam':
19:27:52.530:     - source: 'Camera3' (dshow_input)
19:27:52.530:     - source: 'CGC' (text_gdiplus)
19:27:52.530:     - source: 'BibleShow' (ndi_source)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530: - scene 'Three Cam':
19:27:52.530:     - source: 'Camera 1' (dshow_input)
19:27:52.530:         - filter: 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking)
19:27:52.530:     - source: 'Camera3' (dshow_input)
19:27:52.530:     - source: 'Camera2' (dshow_input)
19:27:52.530: - scene 'Screen':
19:27:52.530:     - source: 'Screen 2' (dshow_input)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530: - scene 'Screen & Cam':
19:27:52.530:     - source: 'Screen 2' (dshow_input)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530:     - source: 'Camera 1' (dshow_input)
19:27:52.530:         - filter: 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking)
19:27:52.530: - scene 'Screen Stage & Audience':
19:27:52.530:     - source: 'Screen 2' (dshow_input)
19:27:52.530:         - monitoring: monitor and output
19:27:52.530:     - source: 'Camera 1' (dshow_input)
19:27:52.530:         - filter: 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking)
19:27:52.530:     - source: 'Camera3' (dshow_input)
19:27:52.530: - scene 'Identification':
19:27:52.530:     - source: 'CGC Address' (image_source)
19:27:52.530: - scene 'Title':
19:27:52.530:     - source: 'Time' (text_gdiplus_v2)
19:27:52.530:     - source: 'Church' (text_gdiplus)
19:27:52.530:     - source: 'Date' (text_gdiplus)
19:27:52.530:     - source: 'Live' (text_gdiplus_v2)
19:27:52.530: - scene 'Bible':
19:27:52.530:     - source: 'Image' (image_source)
19:27:52.530: - scene 'Praise':
19:27:52.530:     - source: 'Image 2' (image_source)
19:27:52.530: - scene '2:00 Count Down':
19:27:52.530:     - source: 'Count down' (ffmpeg_source)
19:27:52.530: - scene 'Opening':
19:27:52.530:     - source: 'Opening Video' (ffmpeg_source)
19:27:52.530:         - monitoring: monitor and output
19:27:52.531: - scene 'Opening Music':
19:27:52.531:     - source: 'Openeing_Music' (ffmpeg_source)
19:27:52.531:         - monitoring: monitor and output
19:27:52.531: - scene 'Closing':
19:27:52.531:     - source: 'Closing Video' (ffmpeg_source)
19:27:52.531:         - monitoring: monitor and output
19:27:52.531: - scene 'Praise and Workship':
19:27:52.531:     - source: 'Camera 1' (dshow_input)
19:27:52.531:         - filter: 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking)
19:27:52.531:     - source: 'CGC' (text_gdiplus)
19:27:52.531:     - source: 'BibleShow' (ndi_source)
19:27:52.531:         - monitoring: monitor and output
19:27:52.531:     - source: 'Stream BibleShow' (ndi_source)
19:27:52.531:     - source: 'Priase Lower Thirds' (ndi_source)
19:27:52.531: ------------------------------------------------
19:27:52.566: ---------------------------------
19:27:52.566: [DShow Device: 'Camera2'] settings updated: 
19:27:52.566: 	video device: Decklink Video Capture (4)
19:27:52.566: 	video path: 
19:27:52.566: 	resolution: 1920x1080
19:27:52.566: 	flip: 0
19:27:52.566: 	fps: 59.94 (interval: 166833)
19:27:52.566: 	format: HDYC
19:27:52.599: ---------------------------------
19:27:52.599: [DShow Device: 'Camera3'] settings updated: 
19:27:52.599: 	video device: Blackmagic WDM Capture (2)
19:27:52.599: 	video path: \\?\decklink#avstream#6&1912feb2&0&0#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\decklinkcapture2
19:27:52.599: 	resolution: 1920x1080
19:27:52.599: 	flip: 0
19:27:52.599: 	fps: 60.00 (interval: 166667)
19:27:52.599: 	format: HDYC
19:27:52.610: 	using video device audio: yes
19:27:52.610: 	sample rate: 48000
19:27:52.610: 	channels: 2
19:27:52.610: 	audio type: Capture
19:27:52.663: [StreamFX] <util::threadpool> Worker 1 caught exception from task (0, 18ca14ed7c0) with message: nvidia::cuda::gstexture: Failed to register resource.
19:27:53.301: [obs-websocket] server started successfully on port 4444
19:27:53.302: [obs-ndi] starting NDI main output with name 'OBS'
19:27:53.310: [obs-websocket] io thread started
19:27:53.329: [obs-ndi] 'OBS': ndi output started
19:27:53.329: [obs-ndi] starting NDI preview output with name 'OBS Preview'
19:27:53.335: [obs-ndi] 'OBS Preview': ndi output started
19:28:12.176: User switched to scene 'Rigth Cam'
19:28:12.870: User switched to scene 'Front Cam'
19:28:13.647: User switched to scene 'Rigth Cam'
19:28:14.195: User switched to scene 'Left Cam'
19:29:40.074: User switched to scene 'Rigth Cam'
19:29:41.673: User switched to scene 'Left Cam'
19:29:42.550: User switched to scene 'Rigth Cam'
19:29:44.493: User switched to scene 'Left Cam'
19:29:51.228: User switched to scene 'Rigth Cam'
19:29:52.300: User switched to scene 'Left Cam'
19:31:13.925: User switched to scene 'Rigth Cam'
19:31:15.479: User switched to scene 'Front Cam'
19:31:17.490: User switched to scene 'Left Cam'
19:31:18.494: User switched to scene 'Rigth Cam'
19:31:19.108: User switched to scene 'Front Cam'
19:31:21.643: User switched to scene 'Left Cam'
19:31:34.591: User removed filter 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking) from source 'Camera 1'
19:31:39.043: User switched to scene 'Rigth Cam'
19:31:49.852: User added filter 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking) to source 'Camera2'
19:31:49.952: [StreamFX] <util::threadpool> Worker 3 caught exception from task (0, 18cc2a5e1b0) with message: nvidia::cuda::gstexture: Failed to register resource.
19:32:08.027: User switched to scene 'Left Cam'
19:33:00.964: User switched to scene 'Rigth Cam'
19:33:02.428: User switched to scene 'Left Cam'
19:34:42.311: [jim-nvenc: 'recording_h264'] settings:
19:34:42.311: 	rate_control: CBR
19:34:42.311: 	bitrate:      20000
19:34:42.311: 	cqp:          20
19:34:42.311: 	keyint:       250
19:34:42.311: 	preset:       mq
19:34:42.311: 	profile:      high
19:34:42.311: 	width:        1920
19:34:42.311: 	height:       1080
19:34:42.311: 	2-pass:       true
19:34:42.311: 	b-frames:     2
19:34:42.311: 	lookahead:    false
19:34:42.311: 	psycho_aq:    true
19:34:42.311: 
19:34:42.372: ---------------------------------
19:34:42.373: [FFmpeg aac encoder: 'Track1'] bitrate: 320, channels: 2, channel_layout: 3
19:34:42.373: 
19:34:42.434: ==== Recording Start ===============================================
19:34:42.434: [ffmpeg muxer: 'adv_file_output'] Writing file 'D:/CGCP/Videos/Raw/2021-06-05 19-34-42.mkv'...
19:36:20.274: [ffmpeg muxer: 'adv_file_output'] Output of file 'D:/CGCP/Videos/Raw/2021-06-05 19-34-42.mkv' stopped
19:36:20.274: Output 'adv_file_output': stopping
19:36:20.274: Output 'adv_file_output': Total frames output: 2923
19:36:20.274: Output 'adv_file_output': Total drawn frames: 2936
19:36:20.275: ==== Recording Stop ================================================
19:36:20.423: warning: 2 frames left in the queue on closing
19:36:22.898: [jim-nvenc: 'recording_h264'] settings:
19:36:22.898: 	rate_control: CBR
19:36:22.898: 	bitrate:      20000
19:36:22.898: 	cqp:          20
19:36:22.898: 	keyint:       250
19:36:22.898: 	preset:       mq
19:36:22.898: 	profile:      high
19:36:22.898: 	width:        1920
19:36:22.898: 	height:       1080
19:36:22.898: 	2-pass:       true
19:36:22.898: 	b-frames:     2
19:36:22.898: 	lookahead:    false
19:36:22.898: 	psycho_aq:    true
19:36:22.898: 
19:36:22.941: ---------------------------------
19:36:22.941: [FFmpeg aac encoder: 'Track1'] bitrate: 320, channels: 2, channel_layout: 3
19:36:22.941: 
19:36:22.964: ==== Recording Start ===============================================
19:36:22.965: [ffmpeg muxer: 'adv_file_output'] Writing file 'D:/CGCP/Videos/Raw/2021-06-05 19-36-22.mkv'...
19:36:27.732: [ffmpeg muxer: 'adv_file_output'] Output of file 'D:/CGCP/Videos/Raw/2021-06-05 19-36-22.mkv' stopped
19:36:27.732: Output 'adv_file_output': stopping
19:36:27.732: Output 'adv_file_output': Total frames output: 130
19:36:27.732: Output 'adv_file_output': Total drawn frames: 143
19:36:27.732: ==== Recording Stop ================================================
19:36:27.902: warning: 2 frames left in the queue on closing
19:36:45.149: User switched to scene 'Rigth Cam'
19:38:38.075: ---------------------------------
19:38:38.075: [DShow Device: 'Camera2'] settings updated: 
19:38:38.075: 	video device: Decklink Video Capture (4)
19:38:38.075: 	video path: 
19:38:38.075: 	resolution: 1920x1080
19:38:38.075: 	flip: 0
19:38:38.075: 	fps: 59.94 (interval: 166833)
19:38:38.075: 	format: HDYC
19:38:40.038: ---------------------------------
19:38:40.038: [DShow Device: 'Camera2'] settings updated: 
19:38:40.038: 	video device: Decklink Video Capture (4)
19:38:40.038: 	video path: 
19:38:40.038: 	resolution: 1920x1080
19:38:40.038: 	flip: 0
19:38:40.038: 	fps: 59.94 (interval: 166833)
19:38:40.038: 	format: HDYC
19:38:44.480: User removed filter 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking) from source 'Camera2'
19:38:49.476: User switched to scene 'Left Cam'
19:39:12.697: User added filter 'NVIDIA Face Tracking' (streamfx-filter-nvidia-face-tracking) to source 'Camera 1'
19:39:12.792: [StreamFX] <util::threadpool> Worker 5 caught exception from task (0, 18cc24b8430) with message: nvidia::cuda::gstexture: Failed to register resource.
19:45:46.015: Max audio buffering reached!
19:45:46.015: adding 746 milliseconds of audio buffering, total audio buffering is now 960 milliseconds (source: Camera3)
19:45:46.015: 
19:45:46.036: Source Camera3 audio is lagging (over by 86221.04 ms) at max audio buffering. Restarting source audio.

**Comment by Xaymar** [comment] 2021-06-06 16:32
**Duplicate of #553**. The face tracking filter is not officially recognized as a feature, and should not be used in production.

**Closed by Xaymar** 2021-06-06 16:32 UTC
Labels: status:help-wanted, type:bug
