### ISSUE TITLE
Nvidia NVENC H265 (FFMpeg) Duplicate in selection drop down...

### ISSUE THREAD

**Issue by SPIKEYPUP** [Xaymar/obs-StreamFX#349] opened 2020-10-02 00:24 UTC
### Description

To preface this, this happened once I went to new release 0.9, this wasn't present in 0.8.3 (iir version correctly)
When going into settings, then output, and in recording section, if you pulldown the encoders selection box, you'll see that the entry is duplicated for H265 NVENC (ffmpeg) for some reason.  When selecting it it is like a fresh encoder with everything defaulted, when going back to my other H265 everything I set is back in place, so it seems they are two seperate objects then.  I'm not sure if this behaviour is by design or not, kind of nice to have "presets" but that's what profiles are for I suppose.  :)  Anyway thanks for your time!

![2020-10-01 17 20 17](https://user-images.githubusercontent.com/27184427/94875725-7ab81300-040a-11eb-9bb4-8196da9c8e5b.png)

[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5315362/DxDiag.txt)

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

**Comment by SPIKEYPUP** [comment] 2020-10-02 00:39
I just realized, is this an artifact of me NOT uninstalling the previous version first?  I totally forgot to do so, perhaps this is why?  Anyway just thought that might be good to know...

**Comment by SPIKEYPUP** [comment] 2020-10-02 01:02
Other elements are duplicated as well, such as under transitions "add shader" appears twice, each leads to a different starting path.  Once I uninstall 0.9.0 and reinstall 0.8.3 it goes back to one instance of the various elements, and if I uninstall further to no streamFX then all elements are removed as expected...

**Comment by Xaymar** [comment] 2020-10-02 01:20
**Not a bug, intentional behavior.**

I changed the internal identifiers for all the components of the plugin to follow the same naming scheme, which meant that I had to add redirectors for configurations that used the older identifiers. This redirector is what you end up seeing as the first entry in that list, as OBS's UI has to actually have the element visible and enabled in order for it to be selected by default. Otherwise you'd get people losing their configuration just because of something being deprecated.

This applies to all libOBS facing components by the way: Sources, Filters, Transitions, Encoders, Outputs, etc. The reason there are duplicate entries in the Transitions menu is likely because the Transitions menu doesn't check if such a Transition is "deprecated". This is technically an upstream bug that has not yet been reported.

**Comment by Xaymar** [comment] 2020-10-10 16:13
Closing as "Won't Fix" since it's not a bug.

**Closed** 2020-10-10 16:12 UTC
Labels: type:support

**Comment by SPIKEYPUP** [comment] 2020-10-10 16:24
Thanks for the explanation, makes complete sense, but I do find it a bit confusing.  As like you said all things get duplicated in a sense label wise I found them popping up all over as I do use the plugin quite a bit :)  What a bummer but I totally understand.  BTW sorry I didn't reply sooner I literally been out for the last month and a half just getting back into the swing of things...  Thanks again for all your hard work!
