### ISSUE TITLE
Installs locale into a wrong location

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#152] opened 2020-04-09 01:03 UTC
### Description
Installs locale into a wrong location

### Expected Behavior
Should install into ```share/obs/obs-plugins/StreamFX``` because that's where the locale files of other plugins are installed.

### System Information
FreeBSD 12.1
Version 0.8.0b1

**Comment by Xaymar** [comment] 2020-04-09 11:10
Duplicate of #151.

**Closed by Xaymar** 2020-04-09 11:10 UTC
