### ISSUE TITLE
"ffmpeg-mux: av_interleaved_write_frame failed: Invalid argument"

### ISSUE THREAD

**Issue by EpicLPer** [Xaymar/obs-StreamFX#382] opened 2020-11-19 23:48 UTC
### Description

Trying to start a recording via "Use same as Stream Encoder" or via "NVENC AVC (via FFmpeg)" results in an error message and the following log output:
```
00:40:44.440: ==== Recording Start ===============================================
00:40:44.440: [ffmpeg muxer: 'adv_file_output'] Writing file 'K:/Videos/Livestream Recordings/2020-11-20 00-40-44.mkv'...
00:40:45.075: [ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for info structure failed
00:40:45.075: [ffmpeg muxer: 'adv_file_output'] ffmpeg-mux: av_interleaved_write_frame failed: Invalid argument
00:40:45.075: [matroska @ 0000022f55d27940] pts (17) < dts (33) in stream 0
00:40:45.075: 
00:40:45.075: [ffmpeg muxer: 'adv_file_output'] Output of file 'K:/Videos/Livestream Recordings/2020-11-20 00-40-44.mkv' stopped
00:40:45.075: Output 'adv_file_output': stopping
00:40:45.075: Output 'adv_file_output': Total frames output: 4
00:40:45.075: Output 'adv_file_output': Total drawn frames: 38
00:40:45.075: ==== Recording Stop ================================================
```
Streaming works fine, however trying to start the Recording results in the above error.  
I'm using the exact same settings that recommended in this blog post: https://blog.xaymar.com/2020/06/24/the-art-of-encoding-with-nvidia-turing-nvenc/

### System Information

- Software Version: StreamFX 0.9.1.0-ad245401, OBS 26.0.2
- Operating System: Windows 10 x64
- Kernel Version: 2004
- CPU: i7-6700K
- GPU: NVidia GTX 1080 AMP Extreme
- RAM: 32GB

**Comment by Xaymar** [comment] 2020-11-20 11:03
Duplicate of #260.

**Closed by Xaymar** 2020-11-20 11:03 UTC
