### ISSUE TITLE
OBS Crash after Closing ( Caused by Dynamic Mask )

### ISSUE THREAD

**Issue by Filgaja** [Xaymar/obs-StreamFX#920] opened 2022-09-13 16:31 UTC
### Operating System

Windows 10 1903 and higher

### OBS Studio Version

28.0.1

### StreamFX Version

0.12.0a117-g0ba2848d

### OBS Studio Log

https://obsproject.com/logs/YOn2aER34b3L9w_L

### OBS Studio Crash Log

https://pastebin.com/inxenxUz
(Body was too long for raw paste crashlog in here

### Current and Expected Behavior

Everything works fine, the mask is shown and also do not make any problems while running.
But when i close OBS Studio it crashes. And this only happen when i apply a dynamic mask filter.

### Steps to Reproduce the Problem

- create scene 1
- create scene 2
- put a colorsource into scene 2  (e.g 200x200px)
- Put a dynamic mask filter on scene 1
- choose scene 2 as dynamic mask.

Close OBS.
Then it crashes and gives me a crash error.

### Any additional Information we need to know?

It took me hours to find out what caused the crash behaviour.
I literally deleted every plugin one by one and finally the crash was gone when i deleted streamFX
Then I used a fresh install of OBS and installed only streamFX. Nothing happened.
I imported my scene collection and it crashed again.
Then I deleted the filter and after the dynamic mask filter was deleted, the crash was gone.
This Crash Behaviour persist since 27.x and older version of streamfx

**Comment by Xaymar** [comment] 2022-09-13 16:47
Duplicate of #819

**Closed by Xaymar** 2022-09-13 16:47 UTC
Labels: bug
