### ISSUE TITLE
Version 0.8.0.0 Is not showing in OBS Filters Plugin 

### ISSUE THREAD

**Issue by Tacehtv1** [Xaymar/obs-StreamFX#251] opened 2020-06-19 00:36 UTC
Version 0.80.0 Is not showing in OBS Filters Plugin after install
I installed OBS- StreamFX 0.8.0.0 with obs 25.08 once i followed the instructions how to install using the zipfile , StreamFX does not show up in filters Menu
![Screenshot_26](https://user-images.githubusercontent.com/67129659/85084392-45105680-b19a-11ea-9142-267d0207e27b.png)

now i isntalled the same version on my 2nd desktop that mirrors my broadcasting computer and it worked just fine. 

### System Information

- Software Version: StreamFX 0.8.0.0 OBS 25.08
- Operating System: windows 10 1909 os buils 18363.900
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU:  Intel i5-8400 @2.80GHZ
- GPU: [e. g. Nvidia 1080 TI
- RAM: 32GB

**Comment by Xaymar** [comment] 2020-06-19 05:51
Please read the installation guide in its entirety, _including the section containing requirements_. For further help, please attach a log file.

**Comment by Casontheweb** [comment] 2020-06-19 10:55
Hi. I am having same problems. All should work, file sare where they are supposed to and I meet all requirements.
Windows pro 64 version 1909
Intel i7-9750 
RTX 2060
16MB Ram
Directx 12
OBS 25.0.8 64-Bit

![image](https://user-images.githubusercontent.com/67148998/85125441-eeebf380-b22b-11ea-97d1-1f74a328d370.png)


![image](https://user-images.githubusercontent.com/67148998/85125507-0cb95880-b22c-11ea-9e77-51ab09d459a6.png)

Please help.

**Comment by skeletonbow** [comment] 2020-06-19 11:24
Everyone having problems with StreamFX not showing up in OBS, it is because you did not install the prerequisites necessary to make the plugin work, which are documented in the installation instructions.  It's not a bug.

**Comment by Casontheweb** [comment] 2020-06-19 11:53
Hi

> Everyone having problems with StreamFX not showing up in OBS, it is because you did not install the prerequisites necessary to make the plugin work, which are documented in the installation instructions. It's not a bug.

Hi Skeleton. I just read your answer. To be honest I am right now in the guide.

https://github.com/Xaymar/obs-StreamFX/wiki/Installation

As far I can see there are no previous software requirements on top than OBS latest version and the requirements for the hardware and operating system. I can feel that is clearly our mistake (in this case mine) but I cannot see where the error is.

As mentioned below is my setup that feels way above the minimum requirements so I kindly ask for support so I can realize what I am missing.

Windows pro 64 version 1909
Intel i7-9750
RTX 2060
16MB Ram
Directx 12
OBS 25.0.8 64-Bit

**Comment by Casontheweb** [comment] 2020-06-19 11:58
12:48:00.293: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:48:00.294: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
12:48:00.323: [AMF] Unable to load 'amfrt64.dll', error code 126.
12:48:00.325: [AMF] AMF Test failed due to one or more errors.
12:48:00.325: Failed to initialize module 'enc-amf.dll'
12:48:00.339: [obs-browser]: Version 2.8.6
12:48:00.340: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
12:48:00.342: NVENC supported
12:48:00.343: [obs-ndi] hello ! (version 4.7.1)
12:48:00.343: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
12:48:00.343: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
12:48:00.346: [obs-ndi] NDI runtime loaded successfully
12:48:00.348: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 15:59:50 Feb  4 2020 4.1.6.0)
12:48:00.364: [obs-websocket] you can haz websockets (version 4.7.0)
12:48:00.364: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.10.1
12:48:00.365: [obs-websocket] module loaded!
12:48:00.367: LoadLibrary failed for '../../obs-plugins/64bit/StreamFX.dll': (null) (126)
12:48:00.367: Module '../../obs-plugins/64bit/StreamFX.dll' not loaded
12:48:00.369: Couldn't find VLC installation, VLC video source disabled
12:48:00.372: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:48:00.373: No blackmagic support

**Comment by Casontheweb** [comment] 2020-06-19 12:11
I have found the problem. The plugin requires VC 2019... honestly I havent seem that mentioned anywhere but would be great to add it. Now it works well. Thanks!

**Comment by skeletonbow** [comment] 2020-06-19 12:26
It is literally mentioned in the Requirements section of the installation guide with a link to download the redist.  People tend to skim the instructions rather than actually reading them in full and end up missing the requirements.

**Comment by Xaymar** [comment] 2020-06-19 14:05
![image](https://user-images.githubusercontent.com/437395/85141179-ab52b300-b246-11ea-9942-4fdfb2a10453.png)

I don't even know anymore.

**Comment by jesusliquido** [comment] 2020-06-27 05:47
mi equipo cumple los requisitos e instale MSVC 2019 pro no se muestra, ademas baje el instalador y no funciona, probé colocar manualmente y tampoco, ayuda

**Comment by jesusliquido** [comment] 2020-06-27 06:18
[log.txt](https://github.com/Xaymar/obs-StreamFX/files/4840048/log.txt)
Ojala puedan ayudarme, hice todo incluso instalando MSVC pero hace crash

**Comment by Xaymar** [comment] 2020-06-27 11:27
@jesusliquido Please speak english.

**Comment by Xaymar** [comment] 2020-06-27 11:27
Closing this as it has been solved by reading the Installation guide.

**Closed by Xaymar** 2020-06-27 11:27 UTC
Labels: question-or-support
