### ISSUE TITLE
0.9.0 fails: error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'

### ISSUE THREAD

**Issue by yurivict** [Xaymar/obs-StreamFX#357] opened 2020-10-10 20:43 UTC
```
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.9.0/source/util/util-curl.hpp:93:9: error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'
                        value.resize(buffer_len);
                             ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from /wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.9.0/source/util/util-curl.cpp:21:
/wrkdirs/usr/ports/multimedia/obs-streamfx/work/obs-StreamFX-0.9.0/source/util/util-curl.hpp:95:16: error: implicit instantiation of undefined template 'std::__1::vector<char, std::__1::allocator<char> >'
                        memcpy(value.data(), buffer, value.size());
                                    ^
```

It looks like a forgotten ```#include <vector>```.

FreeBSD 12.2
clang-10

**Comment by Xaymar** [comment] 2020-10-10 23:21
Duplicate of: https://github.com/Xaymar/obs-StreamFX/issues/348

**Closed** 2020-11-01 23:08 UTC
