### ISSUE TITLE
StreamFX replaces About menu on MacOS

### ISSUE THREAD

**Issue by mtrpires** [Xaymar/obs-StreamFX#323] opened 2020-09-05 18:23 UTC
As per instructions [here](https://github.com/Xaymar/obs-StreamFX/issues/316#issuecomment-681186905) I was able to build StreamFX on the latest version of OBS on macOS. However, when you click ```obs``` -> ```About obs``` you're greeted with:

<img width="624" alt="Screen Shot 2020-09-05 at 15 20 28" src="https://user-images.githubusercontent.com/835712/92311209-80e1dd80-ef8b-11ea-9588-580c166c369f.png">

instead of the ```obs about``` pop up. Is there a fix for this?

**Comment by Xaymar** [comment] 2020-09-05 23:14
Please show a video of this happening, [as there's no logical way for this to happen with the current code.](https://github.com/Xaymar/obs-StreamFX/blob/master/source/ui/ui.cpp#L74)

**Comment by mtrpires** [comment] 2020-09-08 14:05
Sure! [Here it is](https://drive.google.com/file/d/1Cdk9zKlC-ycbk9YbDi35Hc5UwZhh547J/view?usp=sharing). There's also a strange behavior: upon launching, the top menu options are not clickable. They become usable only after I click on the OBS system try icon (it makes it hide OBS) -- you can see that in the beginning of the video. Happy to help investigate this as well.

**Comment by Xaymar** [comment] 2020-09-08 16:33
I've watched the provided footage now, and from what is shown in the video, this is either an undefined behavior from Qt, or a modified version of OBS Studio and StreamFX. The project itself has no such functionality to "hijack" any menu, so this is either broken behavior in OBS Studio, Qt, or a modified project. My guess is that the problem is with OBS Studio on MacOS.

**Comment by mtrpires** [comment] 2020-09-08 19:42
@Xaymar that's interesting. I've created another build, this time vanilla, and the menu loads correctly. The only difference is that it does not include StreamFX. I'm wondering whether it would make sense to report this to the OBS team, considering it's only an issue when I include the plugin to the build workload.

**Comment by Xaymar** [comment] 2020-09-10 00:41
It's probably best to get an actual Mac developer involved into this. I'm not such a person, so maybe one of the OBS developers has an idea what is happening here.

**Comment by mtrpires** [comment] 2020-09-10 03:48
Fair enough. I'll help spread the word. I'm also not a mac developer, but I'm happy to help! <sub><sup>(btw, I helped conclude the pt_BR translation, now it's 100%!)</sup></sub>

**Comment by Xaymar** [comment] 2020-11-09 09:45
Might be related to the same code causing the #379 error.

**Comment by Xaymar** [comment] 2021-01-21 02:31
I've pushed a related fix to master, #428 and #427. Please try with the fix applied, but I can't promise a result.

**Comment by Xaymar** [comment] 2021-01-31 21:58
Can confirm this on Mac. None of the PRs so far fix it.

**Comment by Xaymar** [comment] 2021-04-19 12:09
After a long time of not looking at it, I finally understand the missing piece that caused all of this: Qt defaults all menu items to heuristic scanning. Normally this shouldn't be a problem, but it seems that Qt fails to parse the Info.plist file for OBS Studio, so instead of looking for `About OBS` it instead searches for `About `, which as you might have guessed matches the StreamFX menu entry. This should be resolved once #524 is merged.

**Closed** 2021-04-19 12:19 UTC
Labels: os:mac, status:has-fix, type:bug-or-crash
