### ISSUE TITLE
Error Or Bug in OBS

### ISSUE THREAD

**Issue by MagmaBois** [Xaymar/obs-StreamFX#280] opened 2020-07-21 04:02 UTC
# Description
 Umm, hello, I have been using OBS studio for my Making of youtube videos and it has never happened before so please can Obs Team help me with this, I can't explain everything but I only have a picture.
![Help OBS](https://user-images.githubusercontent.com/68272404/88011446-f3f6d800-cb34-11ea-96e9-1f4e363899e5.png)

**### System Information

- 20.04
- Operating System: Ubuntu.
- Kernel-Version: 4.12 (Linux)
- CPU: Intel i9
- GPU: Nvidia GeForce RTX 2080 Ti
- RAM: 32GB**

**Comment by Xaymar** [comment] 2020-07-21 06:02
Can't say much without a log file.

**Comment by Xaymar** [comment] 2020-07-30 06:20
Same here, if there's no further input within the next 5 days, I'll close this.

**Comment by skeletonbow** [comment] 2020-08-01 04:39
Can you state exactly what the problem is in words, what your expectations are and why they're not being met?  The picture doesn't show or describe any problem, nor indicate why you think this is a problem with the StreamFX plugin.

Looking at the picture I just see a blank unconfigured OBS scene collection with no sources in it.  The sources pane even says "You don't have any sources" and tells you what to do.

If you need help learning how to use the OBS program, you may want to join the OBS forums or Discord server and use the #support-portal to determine which support channel is best for the help you need to learn how to use OBS.

Hope this helps.

**Comment by Xaymar** [comment] 2020-08-04 00:27
5 days have passed, and therefore this is being closed.

**Closed by Xaymar** 2020-08-04 00:27 UTC
Labels: question-or-support
