### ISSUE TITLE
NVENC: Recording never stops with B-Frame Reference not set to Disabled. (Workaround inside!)

### ISSUE THREAD

**Issue by TheRealDadbeard** [Xaymar/obs-StreamFX#260] opened 2020-07-01 02:26 UTC
### Description
I saw your optimized settings on your blog and wanted to try them. Unfortunately I can't stop the recording as it will just be stuck on "Stopping Recording". OBS does not freeze or crash and I have to force close it via Task Manager.

This happens if B-Frame Reference Mode is set to your suggested setting. If I set it to Default then the recording closes fine. Setting it to use every B-Frame will not even start the recording and just throw an error.

Log from a recording and then stopping it https://pastebin.com/Jn3z6MWr

### System Information

- Software Version: OBS 25.0.8 StreamFX 0.8.0
- Operating System: Windows
- Kernel Version: 2004
- CPU: 3700x
- GPU: 2070RTX
- RAM: 16

**Comment by Xaymar** [comment] 2020-07-01 03:07
Both of these are known bugs caused by FFmpegs use of NVENC.

**Comment by TheRealDadbeard** [comment] 2020-07-01 03:52
Thanks for the info. 

So it works without issues when I set it to default. Is default in this context disabled? Or something else?

Any workaround or do we have to wait for it to be fixed by ffmpeg devs?

**Comment by Xaymar** [comment] 2020-07-01 04:47
The value of 'Default' depends on the preset chosen, but usually is 'Disabled' for the majority of them. There's no known workaround other than luck, and since it works fine for streaming (most of the time), waiting for the FFmpeg devs to fix it is probably the only way. While I could apply a workaround, probably, it would likely not do much - similar to the ProRes postprocessing it would likely cost extra performance.

**Comment by TheRealDadbeard** [comment] 2020-07-01 04:52
Oh so while streaming it can be fine. Yeah gonna try this later and see if it works out if not then I'll just use OBS ones until this is maybe fixed in the future.

**Comment by TheRealDadbeard** [comment] 2020-07-02 21:25
Okay can confirm it works without issues while streaming.

**Comment by Xaymar** [comment] 2020-07-05 23:05
Further information, the "Each" mode is only supported for HEVC according to the NVENC manual.

**Comment by Xaymar** [comment] 2020-07-15 13:02
Good news, it's actually fixed in the recent ffmpeg versions. Just need to wait for OBS to update their FFmpeg version.

**Comment by TheRealDadbeard** [comment] 2020-07-16 12:30
Oh thats good news, let's hope the next OBS release has the new ffmpeg version in it.

**Comment by MythionVR** [comment] 2020-07-21 01:02
I'm reporting in with the same issue and glad to hear that there's a fix in the works. 

A side note and not sure if it's completely relevant, when choosing the Encoder I don't have the same option as your settings.
I see "H.264/AVC NVidia NVENC" minus the "(via ffmpeg)" part in the drop down menu. However it includes all the same settings further in the settings guide. Is that the option I should be picking or am I actually missing a dependancy?

**Comment by Xaymar** [comment] 2020-07-21 06:03
@MythionVR The latest version has the (via FFmpeg) name in it.

**Comment by MythionVR** [comment] 2020-07-21 14:09
![g66ewa5](https://user-images.githubusercontent.com/68489744/88065030-f886b500-cb63-11ea-9fb3-60e85b036dbf.png)

This is what I currently have listed in my Encoder options. H.264/AVC NVidia NVENC gives me the same options, but there's no option for FFmpeg despite having StreamFX. Should I create a new thread?

**Comment by Xaymar** [comment] 2020-07-21 15:11
0.8.0 is the latest stable, 0.9.0 is currently in alpha.

**Comment by Xaymar** [comment] 2020-11-08 02:44
Closing this for tracking purposes. FFmpeg has fixed this bug for several months now, the OBS Project just needs to get their version of FFmpeg updated accordingly.

**Closed by Xaymar** 2020-11-08 02:44 UTC
Labels: os:windows, type:support

**Comment by Xaymar** [comment] 2020-12-14 06:29
Fixed by OBS Studio 26.1 and newer, which now uses FFmpeg 4.2.4 + some patches.
