### ISSUE TITLE
OBS can not be focues or closed anymore after showing update notice

### ISSUE THREAD

**Issue by nahakiole** [Xaymar/obs-StreamFX#409] opened 2020-12-09 13:57 UTC
### Description
After I got an update notification from StreamFX and closed it I couldn't interact with the obs studio anymore. It wasn't frozen, but I couldn't click on the window buttons and the buttons in the interface. It was like there was an invisible dialog open that couldn't be closed. 

After updating to the latest version it worked because the update Dialog from StreamFX didn't pop up again, but if there was no such bugfix in the 0.9.2.0-c6fb402d release then you might want to take a look at this.

### System Information
- Software Version: 
     - OBS Studio 26.0.2  (64 Bit)
     - Stream FX 0.9.2.0-c6fb402d
- Operating System: Windows 10
- Kernel Version: Version	10.0.19041 Build 19041
- CPU: i7 3930k
- GPU: GTX 1080
- RAM: 32 GB

**Comment by Xaymar** [comment] 2020-12-09 14:13
This was fixed in 0.9.2. Duplicate of #404, #368.

**Closed by Xaymar** 2020-12-09 14:13 UTC
