### ISSUE TITLE
Audio problems with combination of "Source Mirror" and "Browser Source"

### ISSUE THREAD

**Issue by rse** [Xaymar/obs-StreamFX#448] opened 2021-02-02 22:24 UTC
### Description

I'm using the latest StreamFX 0.9.3 and perhaps there is a bug in the audio mirroring of the "Source Mirror" source or I misunderstood something. In particular, I've an OBS.Ninja/OBS-Studio event setup configured today with the following scene/source combination:

- Technical/preparation scenes "Shared-Person-NN" with a "Browser Source" source for OBS.Ninja and an GDI+ source for event initialization purposes. The Browser Source uses "Control audio via OBS".
- Event scenes "Scene-XX" with a bunch of sources (backround canvas, etc), including "Source Mirror" sources "Scene-XX-Person-NN" which links to the "Shared-Person-NN" sources and which have "Enabled Audio" activated.

(sidenote: the reason for this particular nesting and my use of Source Mirror sources is that the "Shared-Person-NN" scenes are shared in various event scenes "Scene-XX" and in each scene I need different transforms applied for scaling/positioning. Directly nested Scenes as Sources did not work as expected)

In the OBS Studio Audio Mixer I then see that the nested "Browser Source" "Shared-Person-NN" receives the audio, but the "Scene-XX's" "Scene-XX-Person-NN" source does NOT(!). When I record the stream, I also see that when I'm on a scene "Shared-Person-NN" the audio is recorded, but when I'm on a scene "Scene-XX" there is just silence recorded.

Either I'm completely overlooking an important aspect or there is a bug in StreamFX's Source Mirror source when it comes to the audio mirroring. In a previous setup with StreamFX 0.9.2 and a combination of Source Mirror and NDI a similar nesting worked just fine. So, this is either a bug in 0.9.3 or there is a difference if Source Mirror mirrors NDI or a Browser Source.

Do you have any clue where the problem could be? I'll try to downgrade to StreamFX 0.9.2, but according to your Git history there were just two very small changes to source-mirror.cpp and both do not look like related to my problem. But do you have any other ideas why a combination of Source Mirror and NDI worked, but Source Mirror and Browser Source might result in my problem? Is the combination of Source Mirror and Browser Source at least expected to work?

### System Information

- Software Version: StreamFX 0.9.3, OBS Studio 26.1.1
- Operating System: Windows 10
- Kernel Version: 20H2
- CPU: Intel i5
- GPU: NVIDIA RTX 2060
- RAM: 32GB

**Comment by rse** [comment] 2021-02-02 22:31
Ok, I've temporarily downgraded to StreamFX 0.9.2 and unfortunately this did not help. I'm now again on 0.9.3. So, it's not a new bug but perhaps it is really just the combination of "Source Mirror" and "Browser Source"?

**Comment by Xaymar** [comment] 2021-02-03 11:02
It's likely that this is a completely new and up until now undiscovered issue. Can you prepare a scene collection that showcases this issue, so that it's easier to reproduce the problem on my end?

**Comment by rse** [comment] 2021-02-03 23:40
Ok, I've today reduced my particular event setup to really just the mentioned two scenes and in these scenes only the relevant sources are kept. It is now maximum reduced. Find the scene collection in the attached test.json file. I've test-driven it by connecting in Chrome to the URL https://obs.xt.msg.team/#/example/example/sender/720p30/mono/P01/Mr._Example (it is my trampoline for OBS.Ninja, just wait 2 seconds for being redirected). If you have the scene collection open in OBS Studio you should see yourself in both scenes. The "Shared-Person-01" scene is where I ingest the event guests and this is where OBS.Ninja runs in the Browser Source "Shared-Person-01-Video" I mentioned. This Browser Source has "Control audio via OBS" enabled. Then there is "Scene-01" with the "Source Mirror" source named "Scene-01-Placeholder-01" where a particular guest is assigned to the placeholder. This source has "Enabled Audio" enabled. When you now check the Audio Mixer of OBS Studio, you will see that on scene "Shared-Person-01" the "Shared-Person-01-Video" receives audio. When you are on "Scene-01" you see that this is still the case, but the Source Mirror source "Scene-01-Placeholder-01" does not receive the audio. One can double-check it by recording the stream and watch the recording. When on "Scene-01" no audio can be heard. When on scene "Shared-Person-01" audio can be heard.

[test.json.txt](https://github.com/Xaymar/obs-StreamFX/files/5922162/test.json.txt)

**Comment by rse** [comment] 2021-02-06 11:33
I've found out some interesting details:

In my setup the particular nesting is [scene] "Scene-01" > [source-mirror] "Scene-01-Placeholder-01" > [scene] "Shared-Person-01" > [browser-source] "Shared-Person-01-Video". To recap, the ultimate reasons for this particular nesting is: (1) I have to use [source-mirror] instead of directly including the [scene] "Shared-Person-01" or an intermedia [group] wrapping an included [scene] "Shared-Person-01", because I need to individually transform "Shared-Person-01" on "Scene-01", and (2) I nest the entire [scene] "Shared-Person-01" and not directly its contained [browser-source] "Shared-Person-01-Video" because I need to overlay the person with text, too.

But: just for debugging purposes, I now changed the nesting to [scene] "Scene-01" > [source-mirror] "Scene-01-Placeholder-01" > [browser-source] "Shared-Person-01-Video", i.e, I kicked out the intermediate [scene] "Shared-Person-01" and nest its contained [browser-source] directly. This way I loose the text overlay, of course. But anyway, it is just for debugging purposes. AND NOW THE AUDIO COMES THROUGH THE [source-mirror] "Scene-01-Placeholder-01"!

So, we can conclude that it really is a bug either in OBS Studio or StreamFX, but it seems to be not the combination of [source-mirror] > ... > [browser-source] but the combination of [source-mirror] > [scene] > [browser-source]. Once the scene is part of the mirroring, audio stops working. And it doesn't mean that a [source-mirror] > [scene] combination does not work at all. No, my old NDI-based event setup used [source-mirror] > [scene] > [NDI-source] and this worked just fine. But the combination of  [source-mirror] > [scene] > [browser-source] is what is buggy and leads to a broken audio pass-through!

I don't know whether this further information really helps you in fixing this. I've checked your source-mirror.cpp and see that (1) audio is really specially treated, but (2) nothing looks like related to a nested scene or even a nested scene with a deeper nested browser-source. So, I guess it is not a simple coding bug in StreamFX, but really some nasty incompatibilities inside OBS Studio caused by the particular nesting of [source-mirror] > [scene] > [browser-source]. 

Do you have already any clue on your side? I personally do not know the OBS Studio internals at all, so I personally cannot easily try to find the source and fix this nasty bug myself. To be honest, and even I'm away from hacking C/C++ for over two decades now, too (my days of Apache mod_ssl and mod_rewrite are far behind ;-). But our next event is around the corner and I can only try to circumvent this nasty bug by directly embedding the browser sources instead of the entire scenes now. So I would be very happy if we could find a way to fix this nasty bug in any way...

**Comment by Xaymar** [comment] 2021-02-06 13:07
The test file you submitted doesn't work at all. The Browser Source only appears for a short fraction of a second, and has no audio to begin with.

**Comment by rse** [comment] 2021-02-06 22:23
I've copied my supplied test.json.txt file to a completely different notebook with OBS Studio 26.1.1, renamed the file to test.json again (I previously had to rename it for attaching it to this Github issue) and then I imported it into OBS Studio. When I go to "Scene-01" I see the OBS.Ninja trampoline page to occur for 2 seconds and then a black screen with the text "Mr. Example". Once I go to my mentioned URL https://obs.xt.msg.team/#/example/example/sender/720p30/mono/P01/Mr._Example and press "START" OBS.Ninja "beams" me into the "Scene-01" just fine. So, the test.json.txt file seems to work when importing to a different OBS Studio. Perhaps something in your settings causes the problem or you are not able to connect to OBS.Ninja because of some firewalling issues? Sorry, I was not able to further reduce the example. But you could replace the Browser Source URL with whatever source you have at hand which plays audio. Perhaps a YouTube URL could be used, too?

**Comment by Xaymar** [comment] 2021-05-03 19:25
# Closing as User Error
Investigated this due to it being linked by `Imaginator` on Discord who experienced a similar Problem. In both this and their case, it was because of attempting to mirror audio from a `Scene`, not a `Browser Source`. This is expected behavior, as `Scenes` do not carry any audio. This behavior hasn't changed since the addition of the feature.

**Closed by Xaymar** 2021-05-03 19:25 UTC
Labels: good-report, status:testing-required, type:bug
